### ISSUE TITLE
Doesn't work on Firefox?

### ISSUE THREAD

**Issue by ross-spencer** [ross-spencer/demystify-lite#7]
Seeing an exception: 

* `Exception: showOpenFilePicker 16 [pyodide.asm.js:14:219573](https://cdn.jsdelivr.net/pyodide/v0.20.0/full/pyodide.asm.js)`

I'm not sure what's the cause at the minute. Will also need to confirm what happens on Edge or Safari.

**Comment by ross-spencer** [comment]
`showOpenFilePicker()` may not be supported in Firefox: https://caniuse.com/mdn-api_window_showopenfilepicker

**Comment by ross-spencer** [comment]
Supported browsers: 

* Opera
* Edge
* Chrome

Via: https://developer.mozilla.org/en-US/docs/Web/API/Window/showOpenFilePicker

**Comment by ross-spencer** [comment]
I have added a banner to let folks know for now: https://github.com/ross-spencer/demystify-lite/commit/713bc0ff728acd80f997f5bd7edc1639485657c1

![image](https://user-images.githubusercontent.com/1880412/170895653-1260c81b-3f91-4b48-ba48-e53b473c78e6.png)

**Comment by prettybits** [comment]
Should be fixed by #11, although to test this #10 will also be needed to fix compatibility with the latest pyscript version first.

**Comment by ross-spencer** [comment]
Closed via https://github.com/ross-spencer/demystify-lite/pull/11
